### ISSUE TITLE
[1pt] Create Room Model

### ISSUE THREAD

**Issue by adel-gu** [adel-gu/Cherry-Rooms-back-end#17]
- Create the Room Model
- Add Room Model Validation
    - All fields should be present.
    - Description contain max characters of 250.
    - Price and the number of beds should only be positive values.
- Add Room Model Accossiation
- Add Unit testing for room model (Use Rspec)

Follow the ERD below
![Image](https://user-images.githubusercontent.com/68030297/220885789-4e893939-2ece-41b5-92e5-c31098b50447.png)

**Comment by Zuhaib042** [comment]
Hello @adel-gu 
can you please have a look at this pull request https://github.com/adel-gu/Cherry-Rooms-back-end/pull/27
